"""replace default message with per-category AI messages and auto-inactive rule

Revision ID: 06bca61f4cdc
Revises: f4c5b9a6dfab
Create Date: 2026-10-03 19:00:17.393826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bca61f4cdc'
down_revision: Union[str, Sequence[str], None] = 'f4c5b9a6dfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_message_new', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_new_personalize', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('ai_message_active', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_active_personalize', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('ai_message_inactive', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_inactive_personalize', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('auto_inactive_days', sa.Integer(), nullable=True))
        batch_op.drop_column('use_default_message')
        batch_op.drop_column('default_message')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('use_default_message', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('auto_inactive_days')
        batch_op.drop_column('ai_message_inactive_personalize')
        batch_op.drop_column('ai_message_inactive')
        batch_op.drop_column('ai_message_active_personalize')
        batch_op.drop_column('ai_message_active')
        batch_op.drop_column('ai_message_new_personalize')
        batch_op.drop_column('ai_message_new')

    # ### end Alembic commands ###
