"""add message rotation slots for AI messages

Revision ID: 9889438b7810
Revises: 06bca61f4cdc
Create Date: 2026-10-05 07:39:31.353551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9889438b7810'
down_revision: Union[str, Sequence[str], None] = '06bca61f4cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_message_new_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('ai_message_new_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_new_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_new_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_new_4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_new_5', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_new_rotation_index', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('ai_message_active_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('ai_message_active_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_active_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_active_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_active_4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_active_5', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_active_rotation_index', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('ai_message_inactive_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('ai_message_inactive_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_inactive_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_inactive_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_inactive_4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_inactive_5', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_inactive_rotation_index', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.drop_column('ai_message_inactive')
        batch_op.drop_column('ai_message_active')
        batch_op.drop_column('ai_message_new')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_message_new', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_active', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ai_message_inactive', sa.TEXT(), nullable=True))
        batch_op.drop_column('ai_message_inactive_rotation_index')
        batch_op.drop_column('ai_message_inactive_5')
        batch_op.drop_column('ai_message_inactive_4')
        batch_op.drop_column('ai_message_inactive_3')
        batch_op.drop_column('ai_message_inactive_2')
        batch_op.drop_column('ai_message_inactive_1')
        batch_op.drop_column('ai_message_inactive_enabled')
        batch_op.drop_column('ai_message_active_rotation_index')
        batch_op.drop_column('ai_message_active_5')
        batch_op.drop_column('ai_message_active_4')
        batch_op.drop_column('ai_message_active_3')
        batch_op.drop_column('ai_message_active_2')
        batch_op.drop_column('ai_message_active_1')
        batch_op.drop_column('ai_message_active_enabled')
        batch_op.drop_column('ai_message_new_rotation_index')
        batch_op.drop_column('ai_message_new_5')
        batch_op.drop_column('ai_message_new_4')
        batch_op.drop_column('ai_message_new_3')
        batch_op.drop_column('ai_message_new_2')
        batch_op.drop_column('ai_message_new_1')
        batch_op.drop_column('ai_message_new_enabled')

    # ### end Alembic commands ###
