"""add default message fields to user

Revision ID: f4c5b9a6dfab
Revises: 0001
Create Date: 2026-09-29 21:42:30.022774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c5b9a6dfab'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_default_message', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('default_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_message')
        batch_op.drop_column('use_default_message')

    # ### end Alembic commands ###
